### ISSUE TITLE
running cordova plugin add git@github.com:remotium/cordova-plugin-webrtc.git

### ISSUE THREAD

**Issue by scottlu** [remotium/cordova-plugin-webrtc#1]
Thanks for releasing this. I'm finding I get this output on OSX when installing:

$ cordova plugin add git@github.com:remotium/cordova-plugin-webrtc.git
Fetching plugin "git@github.com:remotium/cordova-plugin-webrtc.git" via npm
npm http GET https://registry.npmjs.org/git
npm http 200 https://registry.npmjs.org/git
Fetching from npm failed: No compatible version found: git@'github.com:remotium/cordova-plugin-webrtc.git'
Valid install targets:
["0.1.0","0.1.1","0.1.2","0.1.3","0.1.4","0.1.5"]
Error: No compatible version found: git@'github.com:remotium/cordova-plugin-webrtc.git'
Valid install targets:
["0.1.0","0.1.1","0.1.2","0.1.3","0.1.4","0.1.5"]
    at installTargetsError (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/lib/cache.js:719:10)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/lib/cache.js:638:10
    at saved (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:142:7)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:133:7
    at FSReqWrap.oncomplete (fs.js:95:15)
$ npm -v
2.7.5

**Comment by oNaiPs** [comment]
The new cordova CLI broke the old way of adding plugins from git repositories. I'll try to fix it this week, perhaps by putting it in npm

**Comment by jbsouvestre** [comment]
Can you try running ``cordova plugin add https://github.com/remotium/cordova-plugin-webrtc.git`` instead ?

**Comment by oNaiPs** [comment]
Added the plugin to npm. Now you can add with ```cordova plugin add cordova-plugin-webrtc
