### ISSUE TITLE
"libwebrtc.a" not found

### ISSUE THREAD

**Issue by jithinbaby** [remotium/cordova-plugin-webrtc#10]
during plugin add to intel XDK as third party plugin it show  "Uh oh! '<path to project dir >\plugins\cordova-plugin-webrtc\libs\ios\libwebrtc.a' not found! "

**Comment by oNaiPs** [comment]
This project is deprecated in favor of https://github.com/eface2face/cordova-plugin-iosrtc.
Please use that instead. Thanks
