### ISSUE TITLE
crash on getUserMedia

### ISSUE THREAD

**Issue by wmill** [remotium/cordova-plugin-webrtc#3]
The app is crashing on the following line, 

https://github.com/remotium/cordova-plugin-webrtc/blob/master/src/ios/WebRTCPlugin.m#L461

Apparently during CaptureManager::StartWithBestCaptureFormat in capturemanager.cc

It could be due to a change in the chromium code, could you tell me the revision hash you build against?  That way I can try to replicate your build.

**Comment by oNaiPs** [comment]
@wmill I updated the plugin, it'll now automatically fetch the webrtc lib from CocoaPods libjingle_peerconnection file. Could you check again if the problem got resolved?

Thanks

**Comment by oNaiPs** [comment]
This project is deprecated in favor of https://github.com/eface2face/cordova-plugin-iosrtc.
Please use that instead. Thanks
