### ISSUE TITLE
cordova-plugin-iosrtc

### ISSUE THREAD

**Issue by ibc** [remotium/cordova-plugin-webrtc#4]
For the shake of knowledge you may want to know about [cordova-iosrtc-plugin](https://github.com/eface2face/cordova-plugin-iosrtc/). It does handle some limitation this project exposes in the README (such as non automatic garbage collection or no MediaStream events).

**Comment by oNaiPs** [comment]
Thanks for the heads up @ibc I did not know about your plugin. Didn't try it yet but looks so much complete already! Only reason to use this one ATM is for the iOS6 support. Will def contributing later on!

Thanks

**Comment by ibc** [comment]
iOS6? I assume that no longer exists :)
