### ISSUE TITLE
Cordova IOS 4.0.1 Webview error on build

### ISSUE THREAD

**Issue by klickagent** [remotium/cordova-plugin-webrtc#6]
Hi there

Great job you did with this plugin! I really appreciate your excellent work!
I wanted you to report that under Cordova ios 4.0.1 the build with the plugin fails, because of the error:
no visible @interface for 'CDVPlugin' declares the selector
  'initWithWebView:'
A little bit of research brought me to this issue on github which might help you: https://github.com/shazron/KeychainPlugin/issues/24.

Best regards
Roman

**Comment by adam-hanna** [comment]
Thanks for finding that. Found some more good info here:
https://github.com/apache/cordova-ios/blob/master/guides/API%20changes%20in%204.0.md

**Comment by oNaiPs** [comment]
This project is deprecated in favor of https://github.com/eface2face/cordova-plugin-iosrtc.
Please use that instead. Thanks
