### ISSUE TITLE
Failed to install 'cordova-plugin-webrtc':Error: Cannot find module 'mkdirp'

### ISSUE THREAD

**Issue by itree** [remotium/cordova-plugin-webrtc#8]
cordova version 6.1.1

`cordova plugin add cordova-plugin-webrtc
`
Failed to install 'cordova-plugin-webrtc':Error: Cannot find module 'mkdirp'

This can be fixed by 

`npm install mkdirp`

Just want to report it, shouldn't mkdirp be included in the plugin?

**Comment by oNaiPs** [comment]
This project is deprecated in favor of https://github.com/eface2face/cordova-plugin-iosrtc.
Please use that instead. Thanks
