### ISSUE TITLE
WebRTCPlugin.m:32:19: No visible @interface for 'CDVPlugin' declares the selector 'initWithWebView:'

### ISSUE THREAD

**Issue by itree** [remotium/cordova-plugin-webrtc#9]
This is error I got when try to build any project with this plugin installed.  Seems to be 'cordova 6'

**Comment by cprasmussen** [comment]
Getting the same error.

**Comment by lmbao** [comment]
Getting the same error.

**Comment by sebi-b** [comment]
Same error.... :(

**Comment by mukeschShah** [comment]
confirming this error

**Comment by oNaiPs** [comment]
This project is deprecated in favor of https://github.com/eface2face/cordova-plugin-iosrtc.
Please use that instead. Thanks
